<a href="https://colab.research.google.com/github/itachi0229/EL3/blob/main/Intro_to_numpy_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
price=[2,1,10]
type(price)

list

In [ ]:
quantity_sold=[17,40,1]
type(quantity_sold)

list

In [13]:
price * quantity_sold

TypeError: ignored

In [ ]:
import numpy as np


In [ ]:
price_array=np.array(price)
quantity_sold_array=np.array(quantity_sold)
type(price_array)

numpy.ndarray

In [ ]:
price_array* quantity_sold_array

array([34, 40, 10])

In [3]:
cost array=np.array([0.25,0.50,5.00])

SyntaxError: ignored

In [ ]:
profit_array=price_array-cost_array
print(profit_array)

[1.75 0.5  5.  ]


In [ ]:
profit_array>2.00

array([False, False,  True])

In [ ]:
price_array=price_array+[7]
print(price_array)

[ 9  8 17]


In [ ]:

price_array=price_array-[7]

price_array=np.append(price_array,7)
print(price_array)

[ 2  1 10  7]


In [ ]:
price_array=np.append(price_array,[4.50,3,4,9])
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4.   9. ]


In [ ]:
print(price_array.dtype)

float64


In [ ]:
price_array=np.delete(price_array,-1)
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4. ]


In [ ]:
price_array[2]=12

In [ ]:
print(price_array)

[ 2.   1.  12.   7.   4.5  3.   4. ]


Bakery Numpy Exercise

In [4]:
price = [2, 1, 10]
type(price)

list

In [5]:
quantity_sold = [17, 40, 1]
type(quantity_sold)

list

In [8]:
import numpy as np

In [10]:
price_array = np.array(price)
quantity_sold_array = np.array(quantity_sold)
type(price_array)
type (quantity_sold_array)

numpy.ndarray

In [12]:
price * quantity_sold_array

array([34, 40, 10])